Read quay.io token from sensu config
aboutsource/quayio-scanner pull request #2
Opened 2017-10-23 13:07 UTC by stefan-as

2017-10-23 14:12 UTC, bennibu requested changes
Bis auf den Typo im include siehts gut aus für mich.

2017-10-23 14:12 UTC, bennibu commented on bin/check-container-vulnerabilities.rb
> +  include Sensu::Plugin::Util
Das muss `include Sensu::Plugin::Utils` heißen, oder? https://github.com/sensu-plugins/sensu-plugin/blob/master/lib/sensu-plugin/utils.rb

2017-10-24 08:03 UTC, stefan-as commented
@bennibu ups, typo, gefixt.

2018-06-08 11:24 UTC, stefan-as commented
Obsolet, Sensu kann sowas inzwischen selbst.

2018-06-08 11:24 UTC, closed without merging