Fix rate limiting on scan
aboutsource/quayio-scanner pull request #6
Opened 2020-09-28 13:31 UTC by stefan-as

Der Check ruft zweimal die QuayIO-API auf. Der Schutz gegen Rate-Limiting war aber nur an einem Aufruf implementiert. Ich habe den Moment genutzt, um die API-Calls zu generalisieren und in eine eigene Klasse zu kapseln.

2020-09-29 10:42 UTC, bennibu reviewed
Moin Stefan, du hast ja einiges umgebaut hier. Als zentralen Unterschied zu vorher sehe ich, dass der scanner bei einem 520 oder nach 5 Versuchen austeigt. Vorher hat er bei einem 520 es trotzdem noch 5 mal versucht. Inwieweit soll das das Problem lösen?

2020-09-29 11:18 UTC, stefan-as commented
@bennibu an der Stelle hab ich eigentlich nur die Logik umgedreht, weil sich das besser im Code gemacht hat (bisher: bei 520 und weniger als 5 weitermachen; jetzt: bei nicht 520 oder mehr als 5 aussteigen).

Der relevante Teil ist, dass es zwei API-Calls gibt und bisher nur der erste API-Call abgesichert war. Mit dem neuen Code sind beide API-Calls abgesichert: https://github.com/aboutsource/quayio-scanner/blob/5c6ac6abcf64da7da465e436182aa57bbc1d11d8/lib/quayio/scanner/image.rb#L72-L73

2020-09-29 11:59 UTC, bennibu commented
@stefan-as Kompliziert, aber ich verstehe jetzt. Ist auf jeden Fall deutlich lesbarer als vorher. Danke.

2020-09-30 14:03 UTC, jonathanschlue-as reviewed
VIelen Dank! Habe wie folgt gereviewed:

Die Code-Vorschläge sind als Anmerkungen, nicht als Wünsche gemeint.  
Lass uns über die konzeptionellen Fragen gerne nochmal sprechen.  
Im folgenden noch eine Sache, die mir insgesamt mit dem Repo aufgefallen ist: 

# Review zu Code außerhalb der Änderungen diesen PRs

Anmerkung: Imho ist es Convention im "Root"-File eines Gems alle Dateien in (Sub-)Modulen des Gems (`quayio/scanner/image`, `quayio/scanner/repository`, ...) einzusammeln, und in den einzelnen Files der Module nur noch externe Dependencies (`docker`, `rest-client`, ...) zu requiren. Z.B.:

```ruby
# lib/quayio/scanner.rb

require 'quayio/scanner/check'
require 'quayio/scanner/image'
require 'quayio/scanner/repository'
require 'quayio/scanner/version'

module Quayio
  module Scanner
  end
end
```

Siehe https://github.com/aboutsource/quayio-scanner/blob/16e77a4e76f444708a8ceb2688e6d08c2a101b66/lib/quayio/scanner.rb#L1-L7

2020-09-30 14:03 UTC, jonathanschlue-as commented on lib/quayio/scanner/image.rb
> +        quayio? && image_exists? && scanned? && vulnerabilities_present?
Frage: Ist es sinnvoll, die Frage danach, ob es Vulnerabilities für ein Docker Image gibt, mit nein zu beantworten, wenn wir es nicht wissen?

2020-09-30 14:03 UTC, jonathanschlue-as commented on lib/quayio/scanner/image.rb
>        end
Frage: Das Pattern hier bezweckt, dass der Request nur jeweils einmal passiert, richtig?

Falls ja, ließe sich hier das einfache Memorizer Pattern anwenden:

```ruby
def raw_scan
  @raw_scan ||= @repository.scan(raw_id)
end
```

2020-09-30 14:03 UTC, jonathanschlue-as commented on lib/quayio/scanner/image.rb
>        end
Frage: Das Pattern hier bezweckt, dass der Request nur jeweils einmal passiert, richtig?

Falls ja, ließe sich hier das einfache Memorizer Pattern anwenden:

```ruby
def raw_id
  @raw_id ||= @repository.id(tag)
end
```

2020-09-30 14:03 UTC, jonathanschlue-as commented on lib/quayio/scanner/repository.rb
> +        return api_call("/image/#{id}/security?vulnerabilities=true")
```suggestion
        api_call("/image/#{id}/security?vulnerabilities=true")
```

2020-09-30 14:03 UTC, jonathanschlue-as commented on lib/quayio/scanner/repository.rb
> +        return (result['images'].first)['id']
```suggestion

        (result['images'].first)['id']
```

2020-09-30 14:03 UTC, jonathanschlue-as commented on lib/quayio/scanner/repository.rb
> +            return JSON.parse(response)
Frage: Was ist, wenn Quay.io invalides JSON (z.B. `""`) zurückliefert? Wollen wir hier nicht auch JSON-Parse-Errors behandeln?

2020-10-01 08:11 UTC, stefan-as commented on lib/quayio/scanner/image.rb
> +        quayio? && image_exists? && scanned? && vulnerabilities_present?
Dann bekommst du einen Sensu-Check, der für alle Images, die nicht bei quay.io liegen, immer rot ist und den du per Definition nie grün bekommen kannst, egal, was du tust. Das ist meiner Meinung nach eine Frage des Contracts: Dieser Sensu-Check prüft, ob quay.io Vulnerabilities zu einem Container kennt. Diese Situation ist definiert und actionable. Das bedeutet im Umkehrschluss natürlich nicht, dass der Container nicht vulnerable ist, wenn quay.io nichts dazu kennt.

2020-10-01 09:00 UTC, jonathanschlue-as requested changes
Noch ein paar Ruby-Dinge

2020-10-01 09:00 UTC, jonathanschlue-as commented on lib/quayio/scanner/image.rb
> +        quayio? && image_exists? && scanned? && vulnerabilities_present?
Vorschlag: Ggf. naming anpsasen.

2020-10-01 09:00 UTC, jonathanschlue-as commented on lib/quayio/scanner/image.rb
> +        raw_id
```suggestion
        !!raw_id
```

2020-10-01 09:00 UTC, jonathanschlue-as commented on lib/quayio/scanner/image.rb
> +        repo = name.split(':').first.gsub(%r{quay.io\/}, '')
Hier könnte man mit ausgefeilter Regex etwas sprechender die Teile rausmatchen:

```ruby
@repo, @tag = name.match(NAME_REGEX).named_captures.slice(:repo, :tag).values
```

2020-10-01 09:00 UTC, jonathanschlue-as commented on lib/quayio/scanner/repository.rb
> +        (1..Float::INFINITY).each do |attempt|
```suggestion
        (1..).each do |attempt|
```

2020-10-01 12:30 UTC, stefan-as commented on lib/quayio/scanner/repository.rb
> +            return JSON.parse(response)
Exception -> UNKNOWN check result -> Alert. Dann sehen wir, dass bei quay.io irgendwas nicht stimmt.

2020-10-01 15:02 UTC, stefan-as commented on lib/quayio/scanner/repository.rb
> +        (1..Float::INFINITY).each do |attempt|
@jonathanschlue-as das hat mir RuboCop bzw. Ruby 2.4 um die Ohren gehauen. Ich lass das daher so.

2020-10-01 15:20 UTC, stefan-as commented on lib/quayio/scanner/image.rb
> +        quayio? && image_exists? && scanned? && vulnerabilities_present?
@jonathanschlue-as ich hab hier nochmal eine Weile nachgedacht und mir fällt kein besserer Name ein, der nicht irgendwie redundant wäre. Das ganze Teil heißt `Quayio::Scanner`, jetzt können wir alle entsprechenden Methoden umbenennen in `vulnerable_according_to_quayio`, oder wir gehen davon aus, dass ein quay.io-Scanner nach Vulnerabilities auf quay.io scannt.

Das Ding müsste jetzt auch an allen Ecken umfallen, in denen er davon ausgeht, dass das Image von Quay.io kommt, aber keine plausiblen Daten abzurufen sind. Alle Images, die nicht von Quay.io kommen, sind auch nicht vulnerable laut Quay.io. Das finde ich ich für einen quay.io-Scanner korrektes Verhalten.

2020-10-01 15:23 UTC, merged